apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongtai-openapi
  namespace: iast-prod
  annotations:
    kubesphere.io/description: dongtai-openapi
  labels:
    app: dongtai-openapi
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dongtai-openapi
  template:
    metadata:
      labels:
        app: dongtai-openapi
    spec:
      containers:
        - name: dongtai-openapi-container
          image: dongtai/dongtai-openapi:VERSION
          imagePullPolicy: Always
          volumeMounts:
            - name: configfile
              mountPath: /opt/dongtai/openapi/conf/config.ini
              subPath: config.ini
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi
          env:
            - name: "active.profile"
              value: "PROD"
      volumes:
        - name: configfile
          configMap:
            name: dongtai-iast-config-prod.ini
---
apiVersion: v1
kind: Service
metadata:
  name: dongtai-openapi-svc
  namespace: iast-prod
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: dongtai-openapi
  type: ClusterIP
